# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Firebase App Distribution (prd)"
    lane :distribute_prd do
        # https://docs.fastlane.tools/actions/build_android_app/
        build_android_app(
            tasks: ["assemblePrdDebug", "bundlePrdDebug"]
        )

        # https://firebase.google.com/docs/app-distribution/android/distribute-fastlane
        firebase_app_distribution(
            app: "1:544503818397:android:61fd671f924df9df224c74",
            firebase_cli_token: "1//06DNGTtt3kQAcCgYIARAAGAYSNwF-L9IrZ6UlKnRj1NadYsaKIpWgpPSt0qyyQoH2j7eaECGmvbiLjbOcoy-uX24Djr1U1v2VJMw",
            groups: "prd-testers",
            release_notes: "개발/운영 앱 별도 분리"
        )
    end
end
